# docker-compose.yml
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    env_file:
    - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    depends_on:
      - backend